### ISSUE TITLE
Not a problem, per se

### ISSUE THREAD

**Issue by muxketeer** [xsc/bashing#11]
Hi there. This looks like a great tool. However, I'm not entirely certain what problem this tool solves.
What problem does this tool solve?
It clearly looks like it could be useful for managing something. Just not sure what.

What issue(s) did having this tool, solve for you? 

To me it seems like a lot of overhead to get a semblance of version management. But I'm really curious to understand more about what processes/workflows are made easier by using this tool.

I've read the wiki, and understand what it says there. I'm just not finding the answer to my above question(s) anywhere there. Again, looks like a cool tool. Great work. I'm just not understanding how or when it is best used.

Thanks for any further details.

**Comment by xsc** [comment]
Hey there! Thanks for the question - and bear in mind that it has been 9 years since I last _needed_ this tool. :)

If you're building intricate tools in Bash you can quickly end up with hundreds of lines in a single file. Bashing makes this modular, allowing you to have your common library functions in one place, subtasks in another, etc... Also, there is some boilerplate (e.g. help strings, subtask dispatch) that you don't have to write.

Historically, I've created a long-deprecated tool for Vim plugin management (microbe-vim) that became huge really quickly. Bashing was written to tame it.

These days I'd rather use a different set of technologies when creating larger tooling, and let Bash be for small scripts only.

I hope that gave you some insight!

**Comment by muxketeer** [comment]
Fantastic insight. Thanks for the detailed answer and back story. Cheers!
